### ISSUE TITLE
fxtwitch Embeds are not Showing Clip Videos

### ISSUE THREAD

**Issue by RoyRiv3r** [seriaati/fxtwitch#1]
![image](https://github.com/user-attachments/assets/3ea24188-f867-47d7-bf41-6422e31dd7de)

**Comment by seriaati** [comment]
I can't do much about this unfortunately, the video URL of this particular clip is different from the others. The Twitch API doesn't provide the video URL directly, so fxtwitch uses a [very hacky way](https://github.com/seriaati/fxtwitch/blob/731294f4859210a96c21823623e19f41abcbcc45/main.py#L43) to get it. The most I can do is to include the clip's thumbnail when the video URL is not obtainable.
![image](https://github.com/user-attachments/assets/110e74b4-8a5f-4369-9c52-26598dc38139)

**Comment by seriaati** [comment]
This issue will be kept open in case anyone knows a better way to obtain clip video URLs.

**Comment by seriaati** [comment]
Huge thanks to @RoyRiv3r, the fixer should now work for any clips.
