### ISSUE TITLE
Is you down?

### ISSUE THREAD

**Issue by DarkblooM-IO** [seriaati/fxtwitch#2]
![image](https://github.com/user-attachments/assets/96cf068f-a7c9-4d3f-8240-1279c1b29014)

**Comment by seriaati** [comment]
Can you post the original Twitch clip URL?

**Comment by DarkblooM-IO** [comment]
> Can you post the original Twitch clip URL?

![image](https://github.com/user-attachments/assets/ea47f349-c418-44be-a112-b909c1b42760)

**Comment by seriaati** [comment]
can you paste the link in text instead of a screenshot?

**Comment by DarkblooM-IO** [comment]
> can you paste the link in text instead of a screenshot?

Oh yeah my bad  
https://twitch.tv/zentreya/clip/SpoopySassyGrouseDAESuppy-UdmD3lkG_cshfB2o

**Comment by seriaati** [comment]
@DarkblooM-IO 
it's working for me? https://fxtwitch.seria.moe/zentreya/clip/SpoopySassyGrouseDAESuppy-UdmD3lkG_cshfB2o
![image](https://github.com/user-attachments/assets/2780b047-7479-47f6-bb1d-f527a33ba0ad)

**Comment by DarkblooM-IO** [comment]
> @DarkblooM-IO 
> it's working for me? https://fxtwitch.seria.moe/zentreya/clip/SpoopySassyGrouseDAESuppy-UdmD3lkG_cshfB2o
> ![image](https://github.com/user-attachments/assets/2780b047-7479-47f6-bb1d-f527a33ba0ad)
> 

Oh that's a different domain, does fxtwitch.tv not work anymore?

**Comment by seriaati** [comment]
idk, the domain had always been fxtwitch.seria.moe
i'm not the developer behind fxtwitch.tv

**Comment by DarkblooM-IO** [comment]
> idk, the domain had always been fxtwitch.seria.moe i'm not the developer behind fxtwitch.tv

Ah OK, that's my bad then
